import type { ContextContract } from './types.js'

const approved = 'APPROVED' as const

export const counterpartyRiskContract: ContextContract = {
  id: 'contract-counterparty-risk',
  name: 'Counterparty Risk & Exposure Assurance',
  description: 'Verified context for counterparty exposure, limit utilization, collateral, concentration, and capital-impact analysis.',
  domain: 'financial_services',
  workflow: 'counterparty_exposure_assurance',
  version: '1.0.0',
  releaseStatus: 'PUBLISHED',
  digest: 'sha256:dev-counterparty-contract-1',
  versions: {
    contract: 'counterparty-risk@1.0.0',
    semantic: 'financial-services@0.1.0',
    policy: 'risk-policy@0.1.0',
    bindings: 'counterparty-bindings@0.1.0',
    api: 'compile@1.0',
  },
  competencyQuestions: [
    {
      id: 'cq-counterparty-exposure',
      question: 'What is our net exposure to a counterparty and which portfolios are over limit?',
      expectedAnswerShape: 'Exposure by legal entity and portfolio, limit utilization, collateral, evidence, and affected regulatory reports.',
      impact: 'CRITICAL',
      owner: 'Counterparty Credit Risk',
      testIds: ['test-path-exposure', 'test-abstain-ambiguous-counterparty'],
      operationId: 'risk.counterparty_exposure_assessment',
    },
  ],
  entityTypes: [
    { id: 'counterparty', label: 'Counterparty', description: 'A party against which the enterprise carries financial or contractual exposure.', group: 'Parties', icon: 'CP', properties: [
      { id: 'counterparty.lei', name: 'Legal entity identifier', dataType: 'string', description: 'ISO 17442 legal entity identifier.', required: true, identifier: true },
      { id: 'counterparty.rating', name: 'Internal credit rating', dataType: 'string', description: 'Current approved internal credit grade.' },
      { id: 'counterparty.sector', name: 'Industry sector', dataType: 'string', description: 'Governed industry classification.' },
    ], evidenceStatus: 'DIRECTLY_EVIDENCED', approvalStatus: approved, impact: 'CRITICAL' },
    { id: 'legal_entity', label: 'Legal Entity', description: 'A legally incorporated entity that enters transactions and owns exposure.', group: 'Parties', icon: 'LE', properties: [
      { id: 'legal_entity.jurisdiction', name: 'Jurisdiction', dataType: 'string', description: 'Primary legal jurisdiction.', required: true },
    ], evidenceStatus: 'DIRECTLY_EVIDENCED', approvalStatus: approved, impact: 'CRITICAL' },
    { id: 'instrument', label: 'Instrument', description: 'A contract or security that creates financial rights and obligations.', group: 'Markets', icon: 'IN', properties: [], evidenceStatus: 'TEMPLATE_DERIVED', approvalStatus: approved, impact: 'HIGH' },
    { id: 'position', label: 'Position', description: 'An owned or owed quantity of an instrument at a point in time.', group: 'Markets', icon: 'PO', properties: [
      { id: 'position.notional', name: 'Notional amount', dataType: 'decimal', description: 'Contractual amount used to calculate cash flows.', required: true },
      { id: 'position.currency', name: 'Currency', dataType: 'string', description: 'ISO 4217 notional currency.', required: true },
    ], evidenceStatus: 'DIRECTLY_EVIDENCED', approvalStatus: approved, impact: 'CRITICAL' },
    { id: 'portfolio', label: 'Portfolio', description: 'A governed collection of positions used for risk and performance aggregation.', group: 'Markets', icon: 'PF', properties: [], evidenceStatus: 'DIRECTLY_EVIDENCED', approvalStatus: approved, impact: 'HIGH' },
    { id: 'netting_agreement', label: 'Netting Agreement', description: 'An enforceable agreement that determines which obligations may be netted.', group: 'Risk Controls', icon: 'NA', properties: [], evidenceStatus: 'DIRECTLY_EVIDENCED', approvalStatus: approved, impact: 'CRITICAL' },
    { id: 'collateral', label: 'Collateral', description: 'Assets pledged to mitigate an exposure under an agreement.', group: 'Risk Controls', icon: 'CO', properties: [
      { id: 'collateral.market_value', name: 'Market value', dataType: 'decimal', description: 'Current governed collateral valuation.', required: true },
    ], evidenceStatus: 'DIRECTLY_EVIDENCED', approvalStatus: approved, impact: 'CRITICAL' },
    { id: 'credit_limit', label: 'Credit Limit', description: 'The approved maximum exposure for a governed scope.', group: 'Risk Controls', icon: 'CL', properties: [
      { id: 'credit_limit.amount', name: 'Approved amount', dataType: 'decimal', description: 'Maximum approved exposure for the limit scope.', required: true },
    ], evidenceStatus: 'DECLARED', approvalStatus: approved, impact: 'CRITICAL' },
    { id: 'regulatory_report', label: 'Regulatory Report', description: 'A governed submission containing exposure and capital disclosures.', group: 'Governance', icon: 'RR', properties: [], evidenceStatus: 'TEMPLATE_DERIVED', approvalStatus: approved, impact: 'HIGH' },
  ],
  entities: [
    {
      id: 'CP-0103',
      typeId: 'counterparty',
      label: 'Arcadia Capital Markets LLC',
      aliases: ['Arcadia Capital', 'Arcadia', 'ACM'],
      properties: { lei: '549300ARCADIA0103', rating: 'BBB', sector: 'Financials' },
      evidenceRefs: ['ev-counterparty-master'],
      evidenceStrength: 'EXACT',
      validFrom: '2025-01-01T00:00:00.000Z',
    },
    {
      id: 'CP-0188',
      typeId: 'counterparty',
      label: 'Arcadia Asset Management Ltd',
      aliases: ['Arcadia Asset Management', 'AAM'],
      properties: { lei: '549300ARCADIA0188', rating: 'A-', sector: 'Asset Management' },
      evidenceRefs: ['ev-counterparty-master'],
      evidenceStrength: 'STRONG',
      validFrom: '2025-01-01T00:00:00.000Z',
    },
    { id: 'LE-US-001', typeId: 'legal_entity', label: 'Meridian Bank NA', aliases: ['Meridian US'], properties: { jurisdiction: 'US' }, evidenceRefs: ['ev-legal-entity-registry'], evidenceStrength: 'EXACT', validFrom: '2020-01-01T00:00:00.000Z' },
    { id: 'PF-CREDIT-01', typeId: 'portfolio', label: 'Global Credit Trading', aliases: ['GCT'], properties: { desk: 'Credit' }, evidenceRefs: ['ev-position-ledger'], evidenceStrength: 'EXACT', validFrom: '2025-01-01T00:00:00.000Z' },
    { id: 'INS-IRS-77', typeId: 'instrument', label: 'USD Interest Rate Swap', aliases: ['USD IRS'], properties: { assetClass: 'Rates' }, evidenceRefs: ['ev-position-ledger'], evidenceStrength: 'STRONG', validFrom: '2025-01-01T00:00:00.000Z' },
    { id: 'POS-9931', typeId: 'position', label: 'Arcadia USD IRS Position', aliases: [], properties: { notional: 85000000, currency: 'USD' }, evidenceRefs: ['ev-position-ledger'], evidenceStrength: 'EXACT', validFrom: '2026-07-18T00:00:00.000Z' },
    { id: 'AGR-ISDA-44', typeId: 'netting_agreement', label: 'Arcadia 2022 ISDA Master', aliases: ['Arcadia ISDA'], properties: { enforceability: 'confirmed' }, evidenceRefs: ['ev-isda-opinion'], evidenceStrength: 'STRONG', validFrom: '2022-03-01T00:00:00.000Z' },
    { id: 'COLL-POOL-44', typeId: 'collateral', label: 'Arcadia USD Collateral Pool', aliases: [], properties: { marketValue: 12800000, currency: 'USD' }, evidenceRefs: ['ev-collateral-ledger'], evidenceStrength: 'EXACT', validFrom: '2026-07-18T00:00:00.000Z' },
    { id: 'LIMIT-CP-103', typeId: 'credit_limit', label: 'Arcadia Group Current Exposure Limit', aliases: [], properties: { amount: 25000000, currency: 'USD' }, evidenceRefs: ['ev-limit-policy'], evidenceStrength: 'EXACT', validFrom: '2026-01-01T00:00:00.000Z' },
    { id: 'REPORT-FFIEC-009', typeId: 'regulatory_report', label: 'FFIEC 009 Country Exposure Report', aliases: ['FFIEC 009'], properties: { frequency: 'quarterly' }, evidenceRefs: ['ev-regulatory-catalog'], evidenceStrength: 'STRONG', validFrom: '2024-01-01T00:00:00.000Z' },
  ],
  relationshipTypes: [
    { id: 'trades_with', label: 'TRADES_WITH', sourceTypeId: 'legal_entity', targetTypeId: 'counterparty', cardinality: 'MANY_TO_MANY', description: 'A legal entity has executed trades with a counterparty.', impact: 'CRITICAL' },
    { id: 'references', label: 'REFERENCES', sourceTypeId: 'position', targetTypeId: 'instrument', cardinality: 'MANY_TO_ONE', description: 'A position references an instrument.', impact: 'HIGH' },
    { id: 'held_in', label: 'HELD_IN', sourceTypeId: 'position', targetTypeId: 'portfolio', cardinality: 'MANY_TO_ONE', description: 'A position is aggregated into a portfolio.', impact: 'CRITICAL' },
    { id: 'governed_by', label: 'GOVERNED_BY', sourceTypeId: 'position', targetTypeId: 'netting_agreement', cardinality: 'MANY_TO_ONE', description: 'A position is governed by an enforceable agreement.', impact: 'CRITICAL' },
    { id: 'secured_by', label: 'SECURED_BY', sourceTypeId: 'netting_agreement', targetTypeId: 'collateral', cardinality: 'ONE_TO_MANY', description: 'An agreement is secured by a collateral pool.', impact: 'CRITICAL' },
    { id: 'constrained_by', label: 'CONSTRAINED_BY', sourceTypeId: 'counterparty', targetTypeId: 'credit_limit', cardinality: 'ONE_TO_MANY', description: 'A counterparty exposure is constrained by an approved limit.', impact: 'CRITICAL' },
    { id: 'reported_in', label: 'REPORTED_IN', sourceTypeId: 'counterparty', targetTypeId: 'regulatory_report', cardinality: 'MANY_TO_MANY', description: 'A counterparty exposure contributes to a regulatory report.', impact: 'HIGH' },
  ],
  relationships: [
    { id: 'rel-1', typeId: 'trades_with', sourceEntityId: 'LE-US-001', targetEntityId: 'CP-0103', assertionClass: 'ASSERTED', evidenceRefs: ['ev-position-ledger'], approvalStatus: approved, validFrom: '2025-01-01T00:00:00.000Z' },
    { id: 'rel-2', typeId: 'references', sourceEntityId: 'POS-9931', targetEntityId: 'INS-IRS-77', assertionClass: 'ASSERTED', evidenceRefs: ['ev-position-ledger'], approvalStatus: approved, validFrom: '2026-07-18T00:00:00.000Z' },
    { id: 'rel-3', typeId: 'held_in', sourceEntityId: 'POS-9931', targetEntityId: 'PF-CREDIT-01', assertionClass: 'ASSERTED', evidenceRefs: ['ev-position-ledger'], approvalStatus: approved, validFrom: '2026-07-18T00:00:00.000Z' },
    { id: 'rel-4', typeId: 'governed_by', sourceEntityId: 'POS-9931', targetEntityId: 'AGR-ISDA-44', assertionClass: 'ASSERTED', evidenceRefs: ['ev-isda-opinion'], approvalStatus: approved, validFrom: '2026-07-18T00:00:00.000Z' },
    { id: 'rel-5', typeId: 'secured_by', sourceEntityId: 'AGR-ISDA-44', targetEntityId: 'COLL-POOL-44', assertionClass: 'ASSERTED', evidenceRefs: ['ev-collateral-ledger'], approvalStatus: approved, validFrom: '2026-07-18T00:00:00.000Z' },
    { id: 'rel-6', typeId: 'constrained_by', sourceEntityId: 'CP-0103', targetEntityId: 'LIMIT-CP-103', assertionClass: 'ASSERTED', evidenceRefs: ['ev-limit-policy'], approvalStatus: approved, validFrom: '2026-01-01T00:00:00.000Z' },
    { id: 'rel-7', typeId: 'reported_in', sourceEntityId: 'CP-0103', targetEntityId: 'REPORT-FFIEC-009', assertionClass: 'DERIVED', evidenceRefs: ['ev-regulatory-catalog'], approvalStatus: approved, validFrom: '2026-01-01T00:00:00.000Z' },
  ],
  metrics: [
    { id: 'net_current_exposure', label: 'Net Current Exposure', definition: 'Current positive replacement value after enforceable netting and eligible collateral.', formula: 'max(sum(mark_to_market_by_netting_set) - eligible_collateral, 0)', grain: ['legal_entity', 'counterparty', 'netting_set'], dimensions: ['portfolio', 'currency', 'jurisdiction'], version: '1.0.0', owner: 'Counterparty Credit Risk', approvalStatus: approved },
    { id: 'limit_utilization', label: 'Limit Utilization', definition: 'Governed exposure divided by the approved credit limit for the same scope.', formula: 'governed_exposure / approved_limit', grain: ['counterparty', 'limit_scope'], dimensions: ['legal_entity', 'portfolio'], version: '1.0.0', owner: 'Credit Risk Policy', approvalStatus: approved },
  ],
  evidence: [
    { id: 'ev-counterparty-master', type: 'DATA_BINDING', title: 'Approved counterparty master', source: 'MDM', locator: 'counterparty_master', checksum: 'sha256:counterparty', observedAt: '2026-07-18T14:00:00.000Z', validFrom: '2026-07-18T00:00:00.000Z', status: 'DIRECTLY_EVIDENCED' },
    { id: 'ev-legal-entity-registry', type: 'DATA_BINDING', title: 'Legal entity registry', source: 'Entity Registry', locator: 'legal_entities', checksum: 'sha256:legal', observedAt: '2026-07-18T14:00:00.000Z', validFrom: '2026-07-18T00:00:00.000Z', status: 'DIRECTLY_EVIDENCED' },
    { id: 'ev-position-ledger', type: 'DATA_BINDING', title: 'Trading position ledger', source: 'Risk Warehouse', locator: 'risk.positions_eod', checksum: 'sha256:positions', observedAt: '2026-07-18T23:15:00.000Z', validFrom: '2026-07-18T00:00:00.000Z', status: 'DIRECTLY_EVIDENCED' },
    { id: 'ev-isda-opinion', type: 'DOCUMENT', title: 'ISDA enforceability opinion', source: 'Legal Document Store', locator: 'opinions/arcadia-2026.pdf', checksum: 'sha256:isda', observedAt: '2026-06-01T00:00:00.000Z', validFrom: '2026-01-01T00:00:00.000Z', status: 'DIRECTLY_EVIDENCED' },
    { id: 'ev-collateral-ledger', type: 'DATA_BINDING', title: 'Collateral ledger', source: 'Collateral Platform', locator: 'collateral.current_balances', checksum: 'sha256:collateral', observedAt: '2026-07-18T23:15:00.000Z', validFrom: '2026-07-18T00:00:00.000Z', status: 'DIRECTLY_EVIDENCED' },
    { id: 'ev-limit-policy', type: 'EXPERT_DECISION', title: 'Approved counterparty limit', source: 'Credit Committee', locator: 'decisions/LIMIT-CP-103', checksum: 'sha256:limit', observedAt: '2026-01-02T00:00:00.000Z', validFrom: '2026-01-01T00:00:00.000Z', status: 'DECLARED' },
    { id: 'ev-regulatory-catalog', type: 'TEMPLATE', title: 'Regulatory report applicability map', source: 'Financial Services Pack', locator: 'reports/ffiec-009', checksum: 'sha256:report', observedAt: '2026-07-01T00:00:00.000Z', validFrom: '2026-01-01T00:00:00.000Z', status: 'TEMPLATE_DERIVED' },
  ],
  bindings: [
    { id: 'binding-risk-warehouse@1', sourceSystem: 'Risk Warehouse', operationId: 'risk.counterparty_exposure_assessment', environment: 'production', freshnessMinutes: 1440, requiredPermissions: ['risk.exposure.read'], expectedResultSchema: 'counterparty_exposure_assessment@1', version: '1.0.0', approvalStatus: approved, adapterType: 'OPENAPI', endpoint: 'https://risk.internal/v1/counterparty-exposure', method: 'GET', healthStatus: 'VALID', mappings: [
      { sourcePath: '$.counterparty.lei', targetTypeId: 'counterparty', targetPropertyId: 'counterparty.lei', sourceDataType: 'string', confidence: 'EXACT' },
      { sourcePath: '$.counterparty.rating', targetTypeId: 'counterparty', targetPropertyId: 'counterparty.rating', sourceDataType: 'string', confidence: 'EXACT' },
      { sourcePath: '$.position.notional', targetTypeId: 'position', targetPropertyId: 'position.notional', sourceDataType: 'number', confidence: 'EXACT' },
    ] },
    { id: 'binding-collateral@1', sourceSystem: 'Collateral Platform', operationId: 'risk.counterparty_exposure_assessment', environment: 'production', freshnessMinutes: 60, requiredPermissions: ['risk.collateral.read'], expectedResultSchema: 'collateral_balance@1', version: '1.0.0', approvalStatus: approved, adapterType: 'OPENAPI', endpoint: 'https://collateral.internal/v1/current-balances', method: 'GET', healthStatus: 'VALID', mappings: [
      { sourcePath: '$.marketValue', targetTypeId: 'collateral', targetPropertyId: 'collateral.market_value', sourceDataType: 'number', confidence: 'EXACT' },
    ] },
  ],
  operations: [
    {
      id: 'risk.counterparty_exposure_assessment',
      label: 'Assess counterparty exposure',
      description: 'Resolve a counterparty and compile governed exposure, collateral, limit, portfolio, and reporting context.',
      keywords: ['exposure', 'counterparty', 'credit limit', 'over limit', 'collateral', 'portfolio', 'default', 'rating'],
      requiredEntityTypes: ['counterparty'],
      metricIds: ['net_current_exposure', 'limit_utilization'],
      relationshipPath: ['trades_with', 'held_in', 'governed_by', 'secured_by', 'constrained_by', 'reported_in'],
      sourceBindingIds: ['binding-risk-warehouse@1', 'binding-collateral@1'],
      riskTier: 'PLANNING_DECISION',
      requiredPermissions: ['risk.exposure.read', 'risk.collateral.read'],
      expectedResultSchema: 'counterparty_exposure_assessment@1',
    },
  ],
  policies: [
    { id: 'policy-planning-evidence', label: 'Planning decision evidence', description: 'Planning decisions require strong evidence and current source bindings.', riskTier: 'PLANNING_DECISION', minimumEvidenceStrength: 'STRONG', maximumEvidenceAgeMinutes: 1440, approvalRequired: false, version: '1.0.0', owner: 'Credit Risk Policy', approvalStatus: approved },
  ],
  tests: [
    { id: 'test-path-exposure', type: 'QUESTION', label: 'Exposure path returns portfolios, collateral, limits, and evidence.', status: 'PASS', lastRun: '2026-07-18T23:30:00.000Z', affectedClaimIds: ['trades_with', 'held_in', 'governed_by', 'secured_by', 'constrained_by'] },
    { id: 'test-abstain-ambiguous-counterparty', type: 'ABSTENTION', label: 'Ambiguous Arcadia reference requires clarification.', status: 'PASS', lastRun: '2026-07-18T23:30:00.000Z', affectedClaimIds: ['CP-0103', 'CP-0188'] },
    { id: 'test-binding-freshness', type: 'MAPPING', label: 'Exposure and collateral bindings meet freshness policy.', status: 'PASS', lastRun: '2026-07-18T23:30:00.000Z', affectedClaimIds: ['binding-risk-warehouse@1', 'binding-collateral@1'] },
  ],
  schemaLayout: {
    counterparty: { x: 80, y: 130 },
    legal_entity: { x: 80, y: 280 },
    instrument: { x: 355, y: 60 },
    position: { x: 355, y: 190 },
    portfolio: { x: 355, y: 330 },
    netting_agreement: { x: 640, y: 45 },
    collateral: { x: 640, y: 160 },
    credit_limit: { x: 640, y: 275 },
    regulatory_report: { x: 640, y: 385 },
  },
}
